#!/bin/sh -x
# flock magic
[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -xn "$0" "$0" "$@" ||

BASE_DIR=/projo
export DEBUG=1

for slug in anno miyazaki naoko oshii shinbou; do
    PROJO_DIR=$BASE_DIR/$slug
    python3 $PROJO_DIR/download.py --mirror --fast
    rm -f $PROJO_DIR/index.html
done
