services:
  boinc-client:
    build:
      context: boinc
      dockerfile: client.Containerfile
      cache_from:
        - type=local,src=$DOCKER_BUILD_CACHE/boinc-client
      cache_to:
        - type=local,dest=$DOCKER_BUILD_CACHE/boinc-client
    environment:
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
      - BOINC_GUI_RPC_PASSWORD=$BOINC_GUI_RPC_PASSWORD
    volumes:
      - boinc-data:/var/lib/boinc
    restart: unless-stopped

  boinc-manager:
    build:
      context: boinc
      dockerfile: manager.Containerfile
      cache_from:
        - type=local,src=$DOCKER_BUILD_CACHE/boinc-manager
      cache_to:
        - type=local,dest=$DOCKER_BUILD_CACHE/boinc-manager
    volumes:
      - ./.volumes/boinc-manager:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.boinc-manager.entrypoints=websecure
      - traefik.http.routers.boinc-manager.rule=Host(`boinc.$DOMAIN`)
      - traefik.http.routers.boinc-manager.middlewares=authelia@docker
      - traefik.http.services.boinc-manager-docker.loadbalancer.server.port=5800

volumes:
  boinc-data:
