include:
  - owntracks.compose.yaml

services:
  boinc:
    image: boinc/client:arm64v8@sha256:2031746369792456c0cb03809a4f10d019c516504e23b1ccb649ba518261e0b4
    entrypoint: sh -xc 'apt update && apt install -y libzip-dev && ln -sf libzip.so.5 /lib/aarch64-linux-gnu/libzip.so.4 && start-boinc.sh'
    environment:
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
      - BOINC_GUI_RPC_PASSWORD=$BOINC_GUI_RPC_PASSWORD
    ports:
      - "31416:31416/tcp"
    volumes:
      - boinc-data:/var/lib/boinc
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n:2.11.3
    environment:
      - WEBHOOK_URL=https://n8n.$DOMAIN
    volumes:
      - ./.volumes/n8n:/home/node/.n8n
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.services.n8n-docker.loadbalancer.server.port=5678

  kara:
    image: caddy:2.11.2-alpine
    command: caddy file-server --root /html --browse --access-log
    volumes:
      - ./.volumes/kara:/html:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kara.entrypoints=websecure
      - traefik.http.services.kara-docker.loadbalancer.server.port=80

volumes:
  boinc-data:
