services:
  owntracks-recorder:
    image: owntracks/recorder:1.0.1
    hostname: owntracks-recorder
    environment:
      - OTR_PORT=0
    volumes:
      - ./.volumes/owntracks-recorder:/store
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.owntracks-recorder.entrypoints=websecure
      - traefik.http.routers.owntracks-recorder.rule=Host(`tracks.$DOMAIN`) && Path(`/pub`)
      - traefik.http.routers.owntracks-recorder.middlewares=authelia-basic@docker
      - traefik.http.services.owntracks-recorder-docker.loadbalancer.server.port=8083

  owntracks-frontend:
    image: owntracks/frontend:2.15.3
    environment:
      - SERVER_HOST=owntracks-recorder
      - SERVER_PORT=8083
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.owntracks-frontend.entrypoints=websecure
      - traefik.http.routers.owntracks-frontend.rule=Host(`tracks.$DOMAIN`)
      - traefik.http.routers.owntracks-frontend.middlewares=authelia@docker
      - traefik.http.services.owntracks-frontend-docker.loadbalancer.server.port=80
